In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 835.9 KB

In [58]:
df.describe()

,customer_id,age,purchase_amount,review_rating,previous_purchases,purchase_frequency_days
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750051,25.351538,80.148462
std,1125.977353,15.207589,23.685392,0.713590,14.447125,120.883544
min,1.000000,18.000000,20.000000,2.500000,1.000000,7.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000,14.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000,30.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000,90.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000,365.000000

#### Age is okay std, min, max, 25,50,75 percentile ratio looks like okay,
#### same as Purchase Amount

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

 #### missing value in review rating , we have to fill it with median but we have to make sure about that category never been exchanged when we fill it with median

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

##### make the columns name as snake casing to read and apply query without any error and easy way

In [9]:
df.columns = df.columns.str.lower()

In [11]:
df.columns = df.columns.str.replace(' ','_')

In [14]:
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

##### Create new column `age_group`

In [16]:
bins = [17,25,40,60,100]
labels = ['Young Adult', 'Adult', 'Middle Age', 'Senior']
df['age_group'] = pd.cut(df['age'], bins= bins, labels= labels)

In [24]:
df[['age','age_group']].head()

   age    age_group
0   55   Middle Age
1   19  Young Adult
2   50   Middle Age
3   21  Young Adult
4   45   Middle Age

In [26]:
df['frequency_of_purchases'].unique()

<ArrowStringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

##### create new column purchase_frequnecy_date

In [27]:
frequency_mapping = {

    'Fortnightly':14,
    'Weekly': 7,
    'Annually': 365,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Monthly':30,
    'Every 3 Months': 30
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [33]:
df[['frequency_of_purchases','purchase_frequency_days']].sample(5)

     frequency_of_purchases  purchase_frequency_days
3839              Quarterly                       90
3695            Fortnightly                       14
1485            Fortnightly                       14
2411         Every 3 Months                       30
549               Bi-Weekly                       14

In [36]:
df[['discount_applied','promo_code_used']].sample(10)

     discount_applied promo_code_used
3229               No              No
2877               No              No
27                Yes             Yes
3693               No              No
1718               No              No
711               Yes             Yes
3349               No              No
3375               No              No
3683               No              No
3514               No              No

##### most of the row looks like same lets check if two columns are same then one must be drop

In [39]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

##### this two column are identical so one will be deleted

In [40]:
df = df.drop('promo_code_used', axis = 1)

In [41]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [47]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="7234",
    database="customer_behavior"
)

print("Connected successfully")

Connected successfully

In [50]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:7234@localhost/customer_behavior")

In [51]:
df.to_sql(
    name = 'customers',
    con = engine,
    if_exists= 'replace',
    index = False
)

3900

In [53]:
df['shipping_type'].unique()

<ArrowStringArray>
[       'Express',  'Free Shipping',   'Next Day Air',       'Standard',
 '2-Day Shipping',   'Store Pickup']
Length: 6, dtype: str

In [54]:
df['previous_purchases']

0       14
1        2
2       23
3       49
4       31
        ..
3895    32
3896    41
3897    24
3898    24
3899    33
Name: previous_purchases, Length: 3900, dtype: int64

In [56]:
df['category'].unique()

<ArrowStringArray>
['Clothing', 'Footwear', 'Outerwear', 'Accessories']
Length: 4, dtype: str

In [57]:
df.to_csv('customer_cleaned.csv', index = False)

### Tableau Dashboard

In [63]:
%%html
<iframe 
    src="https://public.tableau.com/views/CustomerBehavior_17749425147970/Dashboard1?:embed=y&:showVizHome=no" 
    width="1280" 
    height="720"
    style="border:none;">
</iframe>